#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://travis-ci.org/
# * native R support: https://github.com/craigcitro/r-travis
# * examples: https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis
# * r-builder: https://github.com/metacran/r-builder
# * covr: https://github.com/jimhester/covr
# * Coveralls: https://coveralls.io/
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------

language: r
dist: trusty
sudo: false
cache: packages
warnings_are_errors: true
# r_build_args: "--compact-vignettes"
# r_check_args: "--as-cran"
r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual --as-cran"

r:
  - release
  - devel

os:
  - linux
  # - osx

r_github_packages:
  - jimhester/covr
  - schloerke/travisDrat

r_packages:
  - covr
  - drat

# - osofr/gridisl
# r_packages:
#   - ggiraph
# - xgboost
# - bindata

addons:
  apt:
    packages:
      - libicu-dev
      - pandoc

env:
 global:
   - CRAN: http://cran.rstudio.com

after_success:
  - travis_wait Rscript -e 'covr::codecov()'

# - travis_wait Rscript -e 'library(covr); coveralls()'
# - Rscript -e "packagedocs::deploy_travis()"
# - Rscript -e "travisDrat::deploy_drat()"

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - RGL_USE_NULL=TRUE
    - PKG_CFLAGS="-O3 -Wall -pedantic"

